import { createSlice } from "@reduxjs/toolkit";

const eventSlice = createSlice({
  name: "event",
  initialState: {
    data: {},
    city: ["Jakarta", "Yogyakarta", "Bandung", "Surabaya"],
    category: ["Seminars", "Festivals", "Match", "Concert"],
    // cities: [
    //   "Jakarta",
    //   "Surabaya",
    //   "Bandung",
    //   "Medan",
    //   "Semarang",
    //   "Makassar",
    //   "Palembang",
    //   "Tangerang",
    //   "Depok",
    //   "Batam",
    //   "Bekasi",
    //   "Bogor",
    //   "Malang",
    //   "Padang",
    //   "Surakarta",
    //   "Bandar Lampung",
    //   "Denpasar",
    //   "Pekanbaru",
    //   "Yogyakarta",
    //   "Cimahi",
    //   "Balikpapan",
    //   "Manado",
    //   "Pontianak",
    //   "Banjarmasin",
    //   "Samarinda",
    //   "Mataram",
    //   "Kupang",
    //   "Jambi",
    //   "Serang",
    //   "Cirebon",
    //   "Ambon",
    //   "Pekalongan",
    //   "Banda Aceh",
    //   "Tasikmalaya",
    //   "Banjarbaru",
    //   "Sukabumi",
    //   "Parepare",
    //   "Magelang",
    //   "Sibolga",
    //   "Purwokerto",
    //   "Pematangsiantar",
    //   "Tegal",
    //   "Salatiga",
    //   "Lhokseumawe",
    //   "Palu",
    //   "Madiun",
    //   "Probolinggo",
    //   "Bitung",
    // ],
  },
  reducers: {
    setData: (state, action) => {
      state.data = action.payload;
    },
  },
});

export const { setData } = eventSlice.actions;
export default eventSlice.reducer;
